name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v1
      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: 12
          always-auth: true
          registry-url: https://npm.pkg.github.com/
          scope: '@srgssr'
      - name: Install dependencies
        env :
          CI: true
        run: npm ci
      - name: Release package to GitHub registry 📦
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.COUSCOUS }}
          NODE_AUTH_TOKEN: ${{ secrets.COUSCOUS }}
        run: npm run release:ci
      - name: Build GitHub Page 🔧
        run: npm run parcel:github:page
      - name: Deploy GitHub Page 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%s%3N')"
      - name: Get minor version
        id: minorversion
        run: |
          PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
          echo "::set-output name=version::${PACKAGE_VERSION%.*}"
          echo "${PACKAGE_VERSION}"
